"""add saved resumes

Revision ID: 141f199ba79e
Revises: 0c3b374364fb
Create Date: 2026-09-30 11:13:44.735477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141f199ba79e'
down_revision: Union[str, Sequence[str], None] = '0c3b374364fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('storage_filename', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_resumes_id'), 'saved_resumes', ['id'], unique=False)
    op.create_index(op.f('ix_saved_resumes_storage_filename'), 'saved_resumes', ['storage_filename'], unique=True)
    op.create_index(op.f('ix_saved_resumes_user_id'), 'saved_resumes', ['user_id'], unique=False)
    op.add_column('tailored_resumes', sa.Column('source_resume_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tailored_resumes_source_resume_id'), 'tailored_resumes', ['source_resume_id'], unique=False)
    op.create_foreign_key(
        "fk_tailored_resumes_source_resume_id",
        "tailored_resumes",
        "saved_resumes",
        ["source_resume_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_tailored_resumes_source_resume_id",
        "tailored_resumes",
        type_="foreignkey",
    )
    op.drop_index(op.f('ix_tailored_resumes_source_resume_id'), table_name='tailored_resumes')
    op.drop_column('tailored_resumes', 'source_resume_id')
    op.drop_index(op.f('ix_saved_resumes_user_id'), table_name='saved_resumes')
    op.drop_index(op.f('ix_saved_resumes_storage_filename'), table_name='saved_resumes')
    op.drop_index(op.f('ix_saved_resumes_id'), table_name='saved_resumes')
    op.drop_table('saved_resumes')
    # ### end Alembic commands ###
