"""add application tracker

Revision ID: 2ad9e9c5e55c
Revises: e4197c5e5eaf
Create Date: 2026-10-02 23:24:11.926958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ad9e9c5e55c'
down_revision: Union[str, Sequence[str], None] = 'e4197c5e5eaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='saved', nullable=False),
    sa.Column('job_url', sa.String(length=2048), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.Date(), nullable=True),
    sa.Column('next_action_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('tailored_resume_id', sa.Integer(), nullable=True),
    sa.Column('cover_letter_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('saved', 'applied', 'screening', 'interview', 'offer', 'rejected', 'withdrawn')", name='ck_applications_status'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['cover_letter_id'], ['cover_letters.id'], ),
    sa.ForeignKeyConstraint(['tailored_resume_id'], ['tailored_resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_analysis_id'), 'applications', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_applications_cover_letter_id'), 'applications', ['cover_letter_id'], unique=False)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_tailored_resume_id'), 'applications', ['tailored_resume_id'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('application_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), server_default='status_changed', nullable=False),
    sa.Column('previous_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("event_type = 'status_changed'", name='ck_application_events_type'),
    sa.CheckConstraint("new_status IN ('saved', 'applied', 'screening', 'interview', 'offer', 'rejected', 'withdrawn')", name='ck_application_events_new_status'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_events_application_id'), 'application_events', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_events_id'), 'application_events', ['id'], unique=False)
    op.create_index(op.f('ix_application_events_user_id'), 'application_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_events_user_id'), table_name='application_events')
    op.drop_index(op.f('ix_application_events_id'), table_name='application_events')
    op.drop_index(op.f('ix_application_events_application_id'), table_name='application_events')
    op.drop_table('application_events')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_tailored_resume_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_cover_letter_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_analysis_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
