"""add cover letters

Revision ID: e4197c5e5eaf
Revises: c34fdd9f62c4
Create Date: 2026-10-02 00:19:09.850671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4197c5e5eaf'
down_revision: Union[str, Sequence[str], None] = 'c34fdd9f62c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cover_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_analysis_id', sa.Integer(), nullable=False),
    sa.Column('source_resume_id', sa.Integer(), nullable=False),
    sa.Column('source_tailored_resume_id', sa.Integer(), nullable=True),
    sa.Column('version_group_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('tone', sa.String(length=20), server_default='professional', nullable=False),
    sa.Column('length', sa.String(length=20), server_default='standard', nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("length IN ('short', 'standard')", name='ck_cover_letters_length'),
    sa.CheckConstraint("status IN ('draft', 'saved')", name='ck_cover_letters_status'),
    sa.CheckConstraint("tone IN ('professional', 'warm', 'concise')", name='ck_cover_letters_tone'),
    sa.ForeignKeyConstraint(['source_analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['source_resume_id'], ['saved_resumes.id'], ),
    sa.ForeignKeyConstraint(['source_tailored_resume_id'], ['tailored_resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'version_group_id', 'version_number', name='uq_cover_letter_version')
    )
    op.create_index(op.f('ix_cover_letters_id'), 'cover_letters', ['id'], unique=False)
    op.create_index(op.f('ix_cover_letters_source_analysis_id'), 'cover_letters', ['source_analysis_id'], unique=False)
    op.create_index(op.f('ix_cover_letters_source_resume_id'), 'cover_letters', ['source_resume_id'], unique=False)
    op.create_index(op.f('ix_cover_letters_source_tailored_resume_id'), 'cover_letters', ['source_tailored_resume_id'], unique=False)
    op.create_index(op.f('ix_cover_letters_user_id'), 'cover_letters', ['user_id'], unique=False)
    op.create_index(op.f('ix_cover_letters_version_group_id'), 'cover_letters', ['version_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cover_letters_version_group_id'), table_name='cover_letters')
    op.drop_index(op.f('ix_cover_letters_user_id'), table_name='cover_letters')
    op.drop_index(op.f('ix_cover_letters_source_tailored_resume_id'), table_name='cover_letters')
    op.drop_index(op.f('ix_cover_letters_source_resume_id'), table_name='cover_letters')
    op.drop_index(op.f('ix_cover_letters_source_analysis_id'), table_name='cover_letters')
    op.drop_index(op.f('ix_cover_letters_id'), table_name='cover_letters')
    op.drop_table('cover_letters')
    # ### end Alembic commands ###
